### PR TITLE
[Bug Fix] Fix Starting Items SQL

### LINKED ISSUE #3764: Database starting_items Table Incorrect Mapping
I'm sure this is known, but it looks like the starting items are not quite right. Classes are getting spells they can't use, or sometimes equipment they shouldn't be able to equip. The latter actually results in the user not being able to do damage until they equip something they can actually use.

Is there already someone working on this? I ask because I would like to contribute if there isn't someone doing it already. I really want to see the 'out of the box' experience for new server owners more streamlined. I checked the current pull requests and issues, and didn't see any mention of this.

Please let me know and I'll get started immediately!

**Example**

Barbarian Berserker
- Item: 1x Backpack
- Item: 20x Break Cakes
- Item: 20x Skin of Milk
- Spell: Minor Healing (Not useable by class)
- Spell: Courage (Not useable by class)
- Primary: Club (Not useable by class)
- Secondary: Gloomingdeep Lantern

### PR DESCRIPTION
**Pull request by Kinglykrab**
# Notes
- `race_list` comes before `class_list`, query had them in the wrong order.

Fixes #3764

### CODE REVIEW

**Review by joligario — APPROVED** [review]

**Comment by Akkadius** [comment]
What's the plan to fix those who already ran this ?

**Comment by joligario** [comment]
[default_starting_items.zip](https://github.com/EQEmu/Server/files/13667154/default_starting_items.zip)

**Comment by Akkadius** [comment]
We need to make this automatic, not require manual intervention

**Comment by joligario** [comment]
> We need to make this automatic, not require manual intervention

That was just me adding some options - not dictating a solutuon.

**Comment by brickbuckett** [comment]
I wasn't positive that everyone else noticed, but to air on the side of caution for anyone watching this issue, you can't simply just apply the backup. column names have changed and you'll have to make additional adjustments to fix:

ALTER TABLE starting_items RENAME COLUMN race TO race_list;
ALTER TABLE starting_items RENAME COLUMN class TO class_list;
ALTER TABLE starting_items RENAME COLUMN itemid TO item_id;

**Comment by Kinglykrab** [comment]
> I wasn't positive that everyone else noticed, but to air on the side of caution for anyone watching this issue, you can't simply just apply the backup. column names have changed and you'll have to make additional adjustments to fix:
> 
> ALTER TABLE starting_items RENAME COLUMN race TO race_list; ALTER TABLE starting_items RENAME COLUMN class TO class_list; ALTER TABLE starting_items RENAME COLUMN itemid TO item_id;

The idea wasn’t to apply the backup. I believe we would just drop the existing table and rerun the query that creates the backup table from the backup table once it has been renamed then run the data translation query to repopulate the new table correctly. How to go about that the best way is the concern. Maybe a new database version would be best.

**Comment by Akkadius** [comment]
My suggestion is a new database migration and flip flop the columns. Don't change the old migration.

You'll need to move one of the columns to a temp name so you can flip the other one without naming conflicts and then complete the shuffle in 3 steps.

**Comment by brickbuckett** [comment]
> The idea wasn’t to apply the backup. I believe we would just drop the existing table and rerun the query that creates the backup table from the backup table once it has been renamed then run the data translation query to repopulate the new table correctly. How to go about that the best way is the concern. Maybe a new database version would be best.

Oh for sure! The end solution will be a permanent fix that can be rolled out without intervention. This is more specific to your OP being edited by Joligario to include a workaround that needed some extra steps to actually be implemented. I have another server on stand-by to test the final solution once we get there.

**Comment by Kinglykrab** [comment]
> My suggestion is a new database migration and flip flop the columns. Don't change the old migration.
> 
> You'll need to move one of the columns to a temp name so you can flip the other one without naming conflicts and then complete the shuffle in 3 steps.

Ended up just doing this.

**Comment by joligario** [comment]
It wasn’t meant as a drop in replacement. It was an option to revert and let you run the SQL again.

File: common/database/database_update_manifest.cpp [hunk 1]
```diff
@@ -5116,6 +5116,21 @@ ALTER TABLE `object` CHANGE COLUMN `unknown20` `incline` int(11) NOT NULL DEFAUL
 ALTER TABLE `keyring`
 ADD COLUMN `id` int UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
 ADD PRIMARY KEY (`id`);
+)"
+	},
+	ManifestEntry{
+		.version = 9247,
+		.description = "2023_12_14_starting_items_fix.sql",
+		.check = "SHOW COLUMNS FROM `starting_items` LIKE 'race_list'",
```
Comment (Akkadius) [inline common/database/database_update_manifest.cpp:5124]: We need something different to anchor on here that no longer be the case after we run the migration. Since we're mutating data we're not anchoring on any schema changes.

If I change my version back 30 versions and re-run everything, I should get all green. If I were to run updates again it will think I need to run this again and error out.

For example, if we also change a field in this migration from say `slot` to `inventory_slot` then we can anchor on something that truly changed schema wise in this migration. We would need to obviously update repository / code but it would make all of this seamless

Comment (Kinglykrab) [reply common/database/database_update_manifest.cpp:5124]: Can we check the order of the columns to confirm that it's correct?

Comment (Akkadius) [reply common/database/database_update_manifest.cpp:5124]: That's a good call out, we could do that

Comment (Kinglykrab) [reply common/database/database_update_manifest.cpp:5124]: Don't think `SHOW COLUMNS` tells us the ordinal position of the column, would we want to assume they have access to `information_schema` database and select its position from there?

Comment (Akkadius) [reply common/database/database_update_manifest.cpp:5124]: Yeah - not everyone gives their server user access to `information_schema` so it may be difficult

**Comment by Akkadius** [comment]
I'll run this through locally and do testing when I get back from errands

**Comment by Akkadius** [comment]
Had to make some tweaks, but here's test output

```
 World |    Info    | CheckVersionsUpToDate ---------------------------------------------------------------------- 
 World |    Info    | CheckVersionsUpToDate   Server | database [9245] binary [9247] checking updates 
 World |    Info    | CheckVersionsUpToDate   Config | [server.auto_database_updates] [true] 
 World |    Info    | CheckVersionsUpToDate ---------------------------------------------------------------------- 
 World |    Info    | UpdateManifest [9246]       [ok] | [2023_12_07_keyring_id.sql] 
 World |    Info    | UpdateManifest [9247]  [missing] | [2023_12_14_starting_items_fix.sql] 
 World |    Info    | UpdateManifest ---------------------------------------------------------------------- 
 World |    Info    | UpdateManifest Automatically backing up database before applying updates 
 World |    Info    | UpdateManifest ---------------------------------------------------------------------- 
 World |    Info    | DatabaseDump MySQL installed [mysql  Ver 15.1 Distrib 10.11.4-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper] 
 World |    Info    | DatabaseDump Database [peq] Host [mariadb] Username [eqemu] 
 World |    Info    | DatabaseDump Database dump created at [backups/peq-2023-12-15.sql] 
 World |    Info    | DatabaseDump Compression requested. Compressing dump [backups/peq-2023-12-15.sql] 
 World |    Info    | DatabaseDump Compressed dump created at [backups/peq-2023-12-15.tar.gz] 
 World |    Info    | UpdateManifest ---------------------------------------------------------------------- 
 World |    Info    | UpdateManifest Running database migrations. Please wait... 
 World |    Info    | UpdateManifest ---------------------------------------------------------------------- 
 World |    Info    | UpdateManifest [9247] [2023_12_14_starting_items_fix.sql] [ok] 
 World |    Info    | UpdateManifest ---------------------------------------------------------------------- 
 World |    Info    | CheckDbUpdates Updates ran successfully, setting database version to [9247] from [9245] 
```

Repositories were updated.

Also looks like we don't do anything with the `status` field for enforcement currently which was missed in the original PR

**Comment by Akkadius** [comment]
**Testing**

Was reported previously that a Barbarian Berserker would get the following per https://github.com/EQEmu/Server/issues/3764

Barbarian Berserker

Item: 1x Backpack
Item: 20x Break Cakes
Item: 20x Skin of Milk
Spell: Minor Healing (Not useable by class)
Spell: Courage (Not useable by class)
Primary: Club (Not useable by class)
Secondary: Gloomingdeep Lantern

image

We seem to be getting the proper items now
