### PR TITLE
[Bug Fix] Send Entity ID in Death Events to resolve #3721

### LINKED ISSUE #3721: zone_controller.pl EVENT_DEATH_ZONE sometimes not providing killed_entity_id
In the code below, if you #kill an npc instantly,  killed_entity_id will have the proper value.  If you aggro the mob first, then damage it down and kill it, then killed_entity_id will be zero all the time.

```
sub EVENT_DEATH_ZONE {
        quest::debug("killed_entity_id:".$killed_entity_id);
        quest::debug("killed_npc_id:".$killed_npc_id);

```
image

image

### PR DESCRIPTION
**Pull request by Kinglykrab**
# Notes
- Due to some pointers becoming invalid you may get an invalid entity ID on the killed mob if we don't just directly send the entity ID in the export string.
- Resolves #3721.

# Screenshot
image

### CODE REVIEW

**Comment by Akkadius** [comment]
Did you test this

**Comment by Kinglykrab** [comment]
> Did you test this

Yes. I can log back ingame to get some screenshot really quick.

**Comment by Kinglykrab** [comment]
`#kill` works fine. Using `#killallnpcs` seems to still result it in exporting as `0` for some reason, but that's not a standard use-case for this event anyway.

File: zone/lua_parser_events.cpp [hunk 1]
```diff
@@ -330,6 +330,9 @@ void handle_npc_death(
 		l_npc_o.push(L);
 		lua_setfield(L, -2, "killed");
 	}
+
```
Comment (Akkadius) [inline zone/lua_parser_events.cpp:333]: Does there become a weird ordering behavior with extra parameters and the extra pointers ?

Comment (Kinglykrab) [reply zone/lua_parser_events.cpp:333]: Shouldn't be any issue since we're exporting them named and the order shouldn't matter much.

I may be able to just remove the `GetID()` export altogether since we now have it functioning properly and don't need this in Lua since we'll have access to the pointer.

**Review by Akkadius — APPROVED** [review]
